#!/bin/bash

usage() {
cat <<EOF
$0: usage: $0 [-f] [-F] [-r <remote>] <rev>
EOF
}

force=
remote=$(git config --get --default origin ptt.remote)
query_only=0

while getopts qfr: ch; do
	case $ch in
	(f)	force="--force-with-lease"
		;;
	(F)	force="--force"
		;;
	(r)	remote="$OPTARG"
		;;

	(q)	query_only=1
		;;

	(\?)	usage >&2
		exit 2
		;;
	esac
done
shift $(( OPTIND - 1 ))

(( $# == 1 )) || { usage >&2; exit 2; }

git rev-list "$@" | tac | while read rev; do
	target=($(git show $rev -q --format=%b | awk '/^x-branch:/ {print $2}'))

	if (( ${#target[*]} > 1 )); then
		echo "ERROR: multiple x-branch directives in $rev." >&2
		exit 1
	elif (( ${#target[*]} == 0 )); then
		continue
	fi

	git show -q --format="%h %s -> %Cred${remote}/${target}%Creset" $rev
	(( $query_only )) && continue
	git push ${force} ${remote} ${rev}:refs/heads/${target}
done
