#!/usr/bin/python

import click
import datetime
import logging
import os
import subprocess
import sys
import yaml

from pathlib import Path

LOG = logging.getLogger('git-synth')


class Git:
    def __init__(self, repo):
        self.repo = Path(repo)

    def __call__(self, *args):
        return self._run_git('-C', self.repo, *args)

    def init(self):
        return self._run_git('init', self.repo)

    def _run_git(self, *args):
        LOG.debug('running with with %s', ' '.join(str(arg) for arg in args))
        return subprocess.check_output(('git',) + args)


def Date(val):
    if val in ['today', 'now']:
        date = datetime.datetime.now()
    else:
        date = datetime.datetime.fromisoformat(val)

    return date


@click.command()
@click.option('-r', '--repo-path', type=Path, required=True)
@click.option('-n', '--name', default='demo')
@click.option('-e', '--email', default='demo@example.com')
@click.option('-d', '--date', type=Date)
@click.option('-v', '--verbose', count=True)
@click.argument('spec', type=click.File(mode='r'), default=sys.stdin)
def main(repo_path, name, date, email, verbose, spec):
    try:
        loglevel = ['WARNING', 'INFO', 'DEBUG'][verbose]
    except IndexError:
        loglevel = 'DEBUG'
    logging.basicConfig(level=loglevel)

    if repo_path.is_dir():
        raise click.ClickException(f'directory {repo_path} already exists')

    git = Git(repo_path)

    os.environ.update({
        'GIT_AUTHOR_NAME': name,
        'GIT_COMMITTER_NAME': name,
        'GIT_AUTHOR_EMAIL': email,
        'GIT_COMMITTER_EMAIL': email,
    })

    if date is not None:
        os.environ['GIT_AUTHOR_DATE'] = date.isoformat()
        os.environ['GIT_COMMITTER_DATE'] = date.isoformat()

    with spec:
        hist = yaml.safe_load(spec)

    stack = [iter(hist)]
    branches = []
    current_branch = None

    git.init()

    while stack:
        actlist = stack.pop()
        try:
            action = next(actlist)
            stack.append(actlist)
        except StopIteration:
            if branches:
                current_branch = branches.pop()
                git('switch', '-q', current_branch)
            continue

        if 'branch' in action:
            spec = action['branch']

            if current_branch is not None:
                branches.append(current_branch)

            LOG.info('creating branch %s', spec['name'])
            git('switch', '-qc', spec['name'])
            current_branch = spec['name']
            stack.append(iter(spec['actions']))
            continue
        elif 'commit' in action:
            spec = action['commit']
            LOG.info('commit with message "%s"', spec['message'])
            git('commit', '-m', spec['message'],
                '--allow-empty')
        elif 'file' in action:
            spec = action['file']
            path = repo_path / spec['name']
            LOG.info('creating file "%s"', spec['name'])
            with path.open('w') as fd:
                fd.write(spec['content'])
            git('add', spec['name'])
        elif 'set' in action:
            spec = action['set']
            if 'date' in spec:
                LOG.info('setting date to "%s"', spec['date'])
                os.environ['GIT_AUTHOR_DATE'] = Date(spec['date']).isoformat()
                os.environ['GIT_COMMITTER_DATE'] = Date(spec['date']).isoformat()
            if 'name' in spec:
                LOG.info('setting name to "%s"', spec['name'])
                os.environ['GIT_AUTHOR_NAME'] = spec['name']
                os.environ['GIT_COMMITTER_NAME'] = spec['name']
            if 'email' in spec:
                LOG.info('setting email to "%s"', spec['email'])
                os.environ['GIT_AUTHOR_EMAIL'] = spec['email']
                os.environ['GIT_COMMITTER_EMAIL'] = spec['email']
        elif 'setenv' in action:
            for k, v in action['setenv'].items():
                LOG.info('setting env var %s to "%s"', k, v)
                os.environ[k] = v


if __name__ == '__main__':
    main()
